apiVersion: v1
kind: Service
metadata:
  name: ubiquity
  labels:
    app: ubiquity
spec:
  ports:
    - port: 9999
      protocol: TCP
      targetPort: 9999
  type: LoadBalancer
  selector:
    app: ubiquity
