// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/IBM/ubiquity/resources"
)

type FakeStorageClient struct {
	ActivateStub        func() error
	activateMutex       sync.RWMutex
	activateArgsForCall []struct{}
	activateReturns     struct {
		result1 error
	}
	activateReturnsOnCall map[int]struct {
		result1 error
	}
	CreateVolumeStub        func(name string, opts map[string]interface{}) error
	createVolumeMutex       sync.RWMutex
	createVolumeArgsForCall []struct {
		name string
		opts map[string]interface{}
	}
	createVolumeReturns struct {
		result1 error
	}
	createVolumeReturnsOnCall map[int]struct {
		result1 error
	}
	RemoveVolumeStub        func(name string) error
	removeVolumeMutex       sync.RWMutex
	removeVolumeArgsForCall []struct {
		name string
	}
	removeVolumeReturns struct {
		result1 error
	}
	removeVolumeReturnsOnCall map[int]struct {
		result1 error
	}
	ListVolumesStub        func() ([]resources.VolumeMetadata, error)
	listVolumesMutex       sync.RWMutex
	listVolumesArgsForCall []struct{}
	listVolumesReturns     struct {
		result1 []resources.VolumeMetadata
		result2 error
	}
	listVolumesReturnsOnCall map[int]struct {
		result1 []resources.VolumeMetadata
		result2 error
	}
	GetVolumeStub        func(name string) (resources.Volume, error)
	getVolumeMutex       sync.RWMutex
	getVolumeArgsForCall []struct {
		name string
	}
	getVolumeReturns struct {
		result1 resources.Volume
		result2 error
	}
	getVolumeReturnsOnCall map[int]struct {
		result1 resources.Volume
		result2 error
	}
	GetVolumeConfigStub        func(name string) (map[string]interface{}, error)
	getVolumeConfigMutex       sync.RWMutex
	getVolumeConfigArgsForCall []struct {
		name string
	}
	getVolumeConfigReturns struct {
		result1 map[string]interface{}
		result2 error
	}
	getVolumeConfigReturnsOnCall map[int]struct {
		result1 map[string]interface{}
		result2 error
	}
	AttachStub        func(name string) (string, error)
	attachMutex       sync.RWMutex
	attachArgsForCall []struct {
		name string
	}
	attachReturns struct {
		result1 string
		result2 error
	}
	attachReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	DetachStub        func(name string) error
	detachMutex       sync.RWMutex
	detachArgsForCall []struct {
		name string
	}
	detachReturns struct {
		result1 error
	}
	detachReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStorageClient) Activate() error {
	fake.activateMutex.Lock()
	ret, specificReturn := fake.activateReturnsOnCall[len(fake.activateArgsForCall)]
	fake.activateArgsForCall = append(fake.activateArgsForCall, struct{}{})
	fake.recordInvocation("Activate", []interface{}{})
	fake.activateMutex.Unlock()
	if fake.ActivateStub != nil {
		return fake.ActivateStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.activateReturns.result1
}

func (fake *FakeStorageClient) ActivateCallCount() int {
	fake.activateMutex.RLock()
	defer fake.activateMutex.RUnlock()
	return len(fake.activateArgsForCall)
}

func (fake *FakeStorageClient) ActivateReturns(result1 error) {
	fake.ActivateStub = nil
	fake.activateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStorageClient) ActivateReturnsOnCall(i int, result1 error) {
	fake.ActivateStub = nil
	if fake.activateReturnsOnCall == nil {
		fake.activateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.activateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStorageClient) CreateVolume(name string, opts map[string]interface{}) error {
	fake.createVolumeMutex.Lock()
	ret, specificReturn := fake.createVolumeReturnsOnCall[len(fake.createVolumeArgsForCall)]
	fake.createVolumeArgsForCall = append(fake.createVolumeArgsForCall, struct {
		name string
		opts map[string]interface{}
	}{name, opts})
	fake.recordInvocation("CreateVolume", []interface{}{name, opts})
	fake.createVolumeMutex.Unlock()
	if fake.CreateVolumeStub != nil {
		return fake.CreateVolumeStub(name, opts)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.createVolumeReturns.result1
}

func (fake *FakeStorageClient) CreateVolumeCallCount() int {
	fake.createVolumeMutex.RLock()
	defer fake.createVolumeMutex.RUnlock()
	return len(fake.createVolumeArgsForCall)
}

func (fake *FakeStorageClient) CreateVolumeArgsForCall(i int) (string, map[string]interface{}) {
	fake.createVolumeMutex.RLock()
	defer fake.createVolumeMutex.RUnlock()
	return fake.createVolumeArgsForCall[i].name, fake.createVolumeArgsForCall[i].opts
}

func (fake *FakeStorageClient) CreateVolumeReturns(result1 error) {
	fake.CreateVolumeStub = nil
	fake.createVolumeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStorageClient) CreateVolumeReturnsOnCall(i int, result1 error) {
	fake.CreateVolumeStub = nil
	if fake.createVolumeReturnsOnCall == nil {
		fake.createVolumeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createVolumeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStorageClient) RemoveVolume(name string) error {
	fake.removeVolumeMutex.Lock()
	ret, specificReturn := fake.removeVolumeReturnsOnCall[len(fake.removeVolumeArgsForCall)]
	fake.removeVolumeArgsForCall = append(fake.removeVolumeArgsForCall, struct {
		name string
	}{name})
	fake.recordInvocation("RemoveVolume", []interface{}{name})
	fake.removeVolumeMutex.Unlock()
	if fake.RemoveVolumeStub != nil {
		return fake.RemoveVolumeStub(name)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.removeVolumeReturns.result1
}

func (fake *FakeStorageClient) RemoveVolumeCallCount() int {
	fake.removeVolumeMutex.RLock()
	defer fake.removeVolumeMutex.RUnlock()
	return len(fake.removeVolumeArgsForCall)
}

func (fake *FakeStorageClient) RemoveVolumeArgsForCall(i int) string {
	fake.removeVolumeMutex.RLock()
	defer fake.removeVolumeMutex.RUnlock()
	return fake.removeVolumeArgsForCall[i].name
}

func (fake *FakeStorageClient) RemoveVolumeReturns(result1 error) {
	fake.RemoveVolumeStub = nil
	fake.removeVolumeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStorageClient) RemoveVolumeReturnsOnCall(i int, result1 error) {
	fake.RemoveVolumeStub = nil
	if fake.removeVolumeReturnsOnCall == nil {
		fake.removeVolumeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.removeVolumeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStorageClient) ListVolumes() ([]resources.VolumeMetadata, error) {
	fake.listVolumesMutex.Lock()
	ret, specificReturn := fake.listVolumesReturnsOnCall[len(fake.listVolumesArgsForCall)]
	fake.listVolumesArgsForCall = append(fake.listVolumesArgsForCall, struct{}{})
	fake.recordInvocation("ListVolumes", []interface{}{})
	fake.listVolumesMutex.Unlock()
	if fake.ListVolumesStub != nil {
		return fake.ListVolumesStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.listVolumesReturns.result1, fake.listVolumesReturns.result2
}

func (fake *FakeStorageClient) ListVolumesCallCount() int {
	fake.listVolumesMutex.RLock()
	defer fake.listVolumesMutex.RUnlock()
	return len(fake.listVolumesArgsForCall)
}

func (fake *FakeStorageClient) ListVolumesReturns(result1 []resources.VolumeMetadata, result2 error) {
	fake.ListVolumesStub = nil
	fake.listVolumesReturns = struct {
		result1 []resources.VolumeMetadata
		result2 error
	}{result1, result2}
}

func (fake *FakeStorageClient) ListVolumesReturnsOnCall(i int, result1 []resources.VolumeMetadata, result2 error) {
	fake.ListVolumesStub = nil
	if fake.listVolumesReturnsOnCall == nil {
		fake.listVolumesReturnsOnCall = make(map[int]struct {
			result1 []resources.VolumeMetadata
			result2 error
		})
	}
	fake.listVolumesReturnsOnCall[i] = struct {
		result1 []resources.VolumeMetadata
		result2 error
	}{result1, result2}
}

func (fake *FakeStorageClient) GetVolume(name string) (resources.Volume, error) {
	fake.getVolumeMutex.Lock()
	ret, specificReturn := fake.getVolumeReturnsOnCall[len(fake.getVolumeArgsForCall)]
	fake.getVolumeArgsForCall = append(fake.getVolumeArgsForCall, struct {
		name string
	}{name})
	fake.recordInvocation("GetVolume", []interface{}{name})
	fake.getVolumeMutex.Unlock()
	if fake.GetVolumeStub != nil {
		return fake.GetVolumeStub(name)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getVolumeReturns.result1, fake.getVolumeReturns.result2
}

func (fake *FakeStorageClient) GetVolumeCallCount() int {
	fake.getVolumeMutex.RLock()
	defer fake.getVolumeMutex.RUnlock()
	return len(fake.getVolumeArgsForCall)
}

func (fake *FakeStorageClient) GetVolumeArgsForCall(i int) string {
	fake.getVolumeMutex.RLock()
	defer fake.getVolumeMutex.RUnlock()
	return fake.getVolumeArgsForCall[i].name
}

func (fake *FakeStorageClient) GetVolumeReturns(result1 resources.Volume, result2 error) {
	fake.GetVolumeStub = nil
	fake.getVolumeReturns = struct {
		result1 resources.Volume
		result2 error
	}{result1, result2}
}

func (fake *FakeStorageClient) GetVolumeReturnsOnCall(i int, result1 resources.Volume, result2 error) {
	fake.GetVolumeStub = nil
	if fake.getVolumeReturnsOnCall == nil {
		fake.getVolumeReturnsOnCall = make(map[int]struct {
			result1 resources.Volume
			result2 error
		})
	}
	fake.getVolumeReturnsOnCall[i] = struct {
		result1 resources.Volume
		result2 error
	}{result1, result2}
}

func (fake *FakeStorageClient) GetVolumeConfig(name string) (map[string]interface{}, error) {
	fake.getVolumeConfigMutex.Lock()
	ret, specificReturn := fake.getVolumeConfigReturnsOnCall[len(fake.getVolumeConfigArgsForCall)]
	fake.getVolumeConfigArgsForCall = append(fake.getVolumeConfigArgsForCall, struct {
		name string
	}{name})
	fake.recordInvocation("GetVolumeConfig", []interface{}{name})
	fake.getVolumeConfigMutex.Unlock()
	if fake.GetVolumeConfigStub != nil {
		return fake.GetVolumeConfigStub(name)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getVolumeConfigReturns.result1, fake.getVolumeConfigReturns.result2
}

func (fake *FakeStorageClient) GetVolumeConfigCallCount() int {
	fake.getVolumeConfigMutex.RLock()
	defer fake.getVolumeConfigMutex.RUnlock()
	return len(fake.getVolumeConfigArgsForCall)
}

func (fake *FakeStorageClient) GetVolumeConfigArgsForCall(i int) string {
	fake.getVolumeConfigMutex.RLock()
	defer fake.getVolumeConfigMutex.RUnlock()
	return fake.getVolumeConfigArgsForCall[i].name
}

func (fake *FakeStorageClient) GetVolumeConfigReturns(result1 map[string]interface{}, result2 error) {
	fake.GetVolumeConfigStub = nil
	fake.getVolumeConfigReturns = struct {
		result1 map[string]interface{}
		result2 error
	}{result1, result2}
}

func (fake *FakeStorageClient) GetVolumeConfigReturnsOnCall(i int, result1 map[string]interface{}, result2 error) {
	fake.GetVolumeConfigStub = nil
	if fake.getVolumeConfigReturnsOnCall == nil {
		fake.getVolumeConfigReturnsOnCall = make(map[int]struct {
			result1 map[string]interface{}
			result2 error
		})
	}
	fake.getVolumeConfigReturnsOnCall[i] = struct {
		result1 map[string]interface{}
		result2 error
	}{result1, result2}
}

func (fake *FakeStorageClient) Attach(name string) (string, error) {
	fake.attachMutex.Lock()
	ret, specificReturn := fake.attachReturnsOnCall[len(fake.attachArgsForCall)]
	fake.attachArgsForCall = append(fake.attachArgsForCall, struct {
		name string
	}{name})
	fake.recordInvocation("Attach", []interface{}{name})
	fake.attachMutex.Unlock()
	if fake.AttachStub != nil {
		return fake.AttachStub(name)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.attachReturns.result1, fake.attachReturns.result2
}

func (fake *FakeStorageClient) AttachCallCount() int {
	fake.attachMutex.RLock()
	defer fake.attachMutex.RUnlock()
	return len(fake.attachArgsForCall)
}

func (fake *FakeStorageClient) AttachArgsForCall(i int) string {
	fake.attachMutex.RLock()
	defer fake.attachMutex.RUnlock()
	return fake.attachArgsForCall[i].name
}

func (fake *FakeStorageClient) AttachReturns(result1 string, result2 error) {
	fake.AttachStub = nil
	fake.attachReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeStorageClient) AttachReturnsOnCall(i int, result1 string, result2 error) {
	fake.AttachStub = nil
	if fake.attachReturnsOnCall == nil {
		fake.attachReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.attachReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeStorageClient) Detach(name string) error {
	fake.detachMutex.Lock()
	ret, specificReturn := fake.detachReturnsOnCall[len(fake.detachArgsForCall)]
	fake.detachArgsForCall = append(fake.detachArgsForCall, struct {
		name string
	}{name})
	fake.recordInvocation("Detach", []interface{}{name})
	fake.detachMutex.Unlock()
	if fake.DetachStub != nil {
		return fake.DetachStub(name)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.detachReturns.result1
}

func (fake *FakeStorageClient) DetachCallCount() int {
	fake.detachMutex.RLock()
	defer fake.detachMutex.RUnlock()
	return len(fake.detachArgsForCall)
}

func (fake *FakeStorageClient) DetachArgsForCall(i int) string {
	fake.detachMutex.RLock()
	defer fake.detachMutex.RUnlock()
	return fake.detachArgsForCall[i].name
}

func (fake *FakeStorageClient) DetachReturns(result1 error) {
	fake.DetachStub = nil
	fake.detachReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStorageClient) DetachReturnsOnCall(i int, result1 error) {
	fake.DetachStub = nil
	if fake.detachReturnsOnCall == nil {
		fake.detachReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.detachReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStorageClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.activateMutex.RLock()
	defer fake.activateMutex.RUnlock()
	fake.createVolumeMutex.RLock()
	defer fake.createVolumeMutex.RUnlock()
	fake.removeVolumeMutex.RLock()
	defer fake.removeVolumeMutex.RUnlock()
	fake.listVolumesMutex.RLock()
	defer fake.listVolumesMutex.RUnlock()
	fake.getVolumeMutex.RLock()
	defer fake.getVolumeMutex.RUnlock()
	fake.getVolumeConfigMutex.RLock()
	defer fake.getVolumeConfigMutex.RUnlock()
	fake.attachMutex.RLock()
	defer fake.attachMutex.RUnlock()
	fake.detachMutex.RLock()
	defer fake.detachMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeStorageClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ resources.StorageClient = new(FakeStorageClient)
