// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/IBM/ubiquity/local/scbe"
)

type FakeScbeRestClient struct {
	CreateVolumeStub        func(string, string, int) (scbe.ScbeVolumeInfo, error)
	createVolumeMutex       sync.RWMutex
	createVolumeArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 int
	}
	createVolumeReturns struct {
		result1 scbe.ScbeVolumeInfo
		result2 error
	}
	createVolumeReturnsOnCall map[int]struct {
		result1 scbe.ScbeVolumeInfo
		result2 error
	}
	DeleteVolumeStub        func(string) error
	deleteVolumeMutex       sync.RWMutex
	deleteVolumeArgsForCall []struct {
		arg1 string
	}
	deleteVolumeReturns struct {
		result1 error
	}
	deleteVolumeReturnsOnCall map[int]struct {
		result1 error
	}
	GetVolMappingStub        func(string) (scbe.ScbeVolumeMapInfo, error)
	getVolMappingMutex       sync.RWMutex
	getVolMappingArgsForCall []struct {
		arg1 string
	}
	getVolMappingReturns struct {
		result1 scbe.ScbeVolumeMapInfo
		result2 error
	}
	getVolMappingReturnsOnCall map[int]struct {
		result1 scbe.ScbeVolumeMapInfo
		result2 error
	}
	GetVolumesStub        func(string) ([]scbe.ScbeVolumeInfo, error)
	getVolumesMutex       sync.RWMutex
	getVolumesArgsForCall []struct {
		arg1 string
	}
	getVolumesReturns struct {
		result1 []scbe.ScbeVolumeInfo
		result2 error
	}
	getVolumesReturnsOnCall map[int]struct {
		result1 []scbe.ScbeVolumeInfo
		result2 error
	}
	LoginStub        func() error
	loginMutex       sync.RWMutex
	loginArgsForCall []struct {
	}
	loginReturns struct {
		result1 error
	}
	loginReturnsOnCall map[int]struct {
		result1 error
	}
	MapVolumeStub        func(string, string) (scbe.ScbeResponseMapping, error)
	mapVolumeMutex       sync.RWMutex
	mapVolumeArgsForCall []struct {
		arg1 string
		arg2 string
	}
	mapVolumeReturns struct {
		result1 scbe.ScbeResponseMapping
		result2 error
	}
	mapVolumeReturnsOnCall map[int]struct {
		result1 scbe.ScbeResponseMapping
		result2 error
	}
	ServiceExistStub        func(string) (bool, error)
	serviceExistMutex       sync.RWMutex
	serviceExistArgsForCall []struct {
		arg1 string
	}
	serviceExistReturns struct {
		result1 bool
		result2 error
	}
	serviceExistReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	UnmapVolumeStub        func(string, string) error
	unmapVolumeMutex       sync.RWMutex
	unmapVolumeArgsForCall []struct {
		arg1 string
		arg2 string
	}
	unmapVolumeReturns struct {
		result1 error
	}
	unmapVolumeReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeScbeRestClient) CreateVolume(arg1 string, arg2 string, arg3 int) (scbe.ScbeVolumeInfo, error) {
	fake.createVolumeMutex.Lock()
	ret, specificReturn := fake.createVolumeReturnsOnCall[len(fake.createVolumeArgsForCall)]
	fake.createVolumeArgsForCall = append(fake.createVolumeArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 int
	}{arg1, arg2, arg3})
	fake.recordInvocation("CreateVolume", []interface{}{arg1, arg2, arg3})
	fake.createVolumeMutex.Unlock()
	if fake.CreateVolumeStub != nil {
		return fake.CreateVolumeStub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.createVolumeReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeScbeRestClient) CreateVolumeCallCount() int {
	fake.createVolumeMutex.RLock()
	defer fake.createVolumeMutex.RUnlock()
	return len(fake.createVolumeArgsForCall)
}

func (fake *FakeScbeRestClient) CreateVolumeCalls(stub func(string, string, int) (scbe.ScbeVolumeInfo, error)) {
	fake.createVolumeMutex.Lock()
	defer fake.createVolumeMutex.Unlock()
	fake.CreateVolumeStub = stub
}

func (fake *FakeScbeRestClient) CreateVolumeArgsForCall(i int) (string, string, int) {
	fake.createVolumeMutex.RLock()
	defer fake.createVolumeMutex.RUnlock()
	argsForCall := fake.createVolumeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeScbeRestClient) CreateVolumeReturns(result1 scbe.ScbeVolumeInfo, result2 error) {
	fake.createVolumeMutex.Lock()
	defer fake.createVolumeMutex.Unlock()
	fake.CreateVolumeStub = nil
	fake.createVolumeReturns = struct {
		result1 scbe.ScbeVolumeInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeScbeRestClient) CreateVolumeReturnsOnCall(i int, result1 scbe.ScbeVolumeInfo, result2 error) {
	fake.createVolumeMutex.Lock()
	defer fake.createVolumeMutex.Unlock()
	fake.CreateVolumeStub = nil
	if fake.createVolumeReturnsOnCall == nil {
		fake.createVolumeReturnsOnCall = make(map[int]struct {
			result1 scbe.ScbeVolumeInfo
			result2 error
		})
	}
	fake.createVolumeReturnsOnCall[i] = struct {
		result1 scbe.ScbeVolumeInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeScbeRestClient) DeleteVolume(arg1 string) error {
	fake.deleteVolumeMutex.Lock()
	ret, specificReturn := fake.deleteVolumeReturnsOnCall[len(fake.deleteVolumeArgsForCall)]
	fake.deleteVolumeArgsForCall = append(fake.deleteVolumeArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("DeleteVolume", []interface{}{arg1})
	fake.deleteVolumeMutex.Unlock()
	if fake.DeleteVolumeStub != nil {
		return fake.DeleteVolumeStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.deleteVolumeReturns
	return fakeReturns.result1
}

func (fake *FakeScbeRestClient) DeleteVolumeCallCount() int {
	fake.deleteVolumeMutex.RLock()
	defer fake.deleteVolumeMutex.RUnlock()
	return len(fake.deleteVolumeArgsForCall)
}

func (fake *FakeScbeRestClient) DeleteVolumeCalls(stub func(string) error) {
	fake.deleteVolumeMutex.Lock()
	defer fake.deleteVolumeMutex.Unlock()
	fake.DeleteVolumeStub = stub
}

func (fake *FakeScbeRestClient) DeleteVolumeArgsForCall(i int) string {
	fake.deleteVolumeMutex.RLock()
	defer fake.deleteVolumeMutex.RUnlock()
	argsForCall := fake.deleteVolumeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeScbeRestClient) DeleteVolumeReturns(result1 error) {
	fake.deleteVolumeMutex.Lock()
	defer fake.deleteVolumeMutex.Unlock()
	fake.DeleteVolumeStub = nil
	fake.deleteVolumeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeScbeRestClient) DeleteVolumeReturnsOnCall(i int, result1 error) {
	fake.deleteVolumeMutex.Lock()
	defer fake.deleteVolumeMutex.Unlock()
	fake.DeleteVolumeStub = nil
	if fake.deleteVolumeReturnsOnCall == nil {
		fake.deleteVolumeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteVolumeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeScbeRestClient) GetVolMapping(arg1 string) (scbe.ScbeVolumeMapInfo, error) {
	fake.getVolMappingMutex.Lock()
	ret, specificReturn := fake.getVolMappingReturnsOnCall[len(fake.getVolMappingArgsForCall)]
	fake.getVolMappingArgsForCall = append(fake.getVolMappingArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("GetVolMapping", []interface{}{arg1})
	fake.getVolMappingMutex.Unlock()
	if fake.GetVolMappingStub != nil {
		return fake.GetVolMappingStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getVolMappingReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeScbeRestClient) GetVolMappingCallCount() int {
	fake.getVolMappingMutex.RLock()
	defer fake.getVolMappingMutex.RUnlock()
	return len(fake.getVolMappingArgsForCall)
}

func (fake *FakeScbeRestClient) GetVolMappingCalls(stub func(string) (scbe.ScbeVolumeMapInfo, error)) {
	fake.getVolMappingMutex.Lock()
	defer fake.getVolMappingMutex.Unlock()
	fake.GetVolMappingStub = stub
}

func (fake *FakeScbeRestClient) GetVolMappingArgsForCall(i int) string {
	fake.getVolMappingMutex.RLock()
	defer fake.getVolMappingMutex.RUnlock()
	argsForCall := fake.getVolMappingArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeScbeRestClient) GetVolMappingReturns(result1 scbe.ScbeVolumeMapInfo, result2 error) {
	fake.getVolMappingMutex.Lock()
	defer fake.getVolMappingMutex.Unlock()
	fake.GetVolMappingStub = nil
	fake.getVolMappingReturns = struct {
		result1 scbe.ScbeVolumeMapInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeScbeRestClient) GetVolMappingReturnsOnCall(i int, result1 scbe.ScbeVolumeMapInfo, result2 error) {
	fake.getVolMappingMutex.Lock()
	defer fake.getVolMappingMutex.Unlock()
	fake.GetVolMappingStub = nil
	if fake.getVolMappingReturnsOnCall == nil {
		fake.getVolMappingReturnsOnCall = make(map[int]struct {
			result1 scbe.ScbeVolumeMapInfo
			result2 error
		})
	}
	fake.getVolMappingReturnsOnCall[i] = struct {
		result1 scbe.ScbeVolumeMapInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeScbeRestClient) GetVolumes(arg1 string) ([]scbe.ScbeVolumeInfo, error) {
	fake.getVolumesMutex.Lock()
	ret, specificReturn := fake.getVolumesReturnsOnCall[len(fake.getVolumesArgsForCall)]
	fake.getVolumesArgsForCall = append(fake.getVolumesArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("GetVolumes", []interface{}{arg1})
	fake.getVolumesMutex.Unlock()
	if fake.GetVolumesStub != nil {
		return fake.GetVolumesStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getVolumesReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeScbeRestClient) GetVolumesCallCount() int {
	fake.getVolumesMutex.RLock()
	defer fake.getVolumesMutex.RUnlock()
	return len(fake.getVolumesArgsForCall)
}

func (fake *FakeScbeRestClient) GetVolumesCalls(stub func(string) ([]scbe.ScbeVolumeInfo, error)) {
	fake.getVolumesMutex.Lock()
	defer fake.getVolumesMutex.Unlock()
	fake.GetVolumesStub = stub
}

func (fake *FakeScbeRestClient) GetVolumesArgsForCall(i int) string {
	fake.getVolumesMutex.RLock()
	defer fake.getVolumesMutex.RUnlock()
	argsForCall := fake.getVolumesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeScbeRestClient) GetVolumesReturns(result1 []scbe.ScbeVolumeInfo, result2 error) {
	fake.getVolumesMutex.Lock()
	defer fake.getVolumesMutex.Unlock()
	fake.GetVolumesStub = nil
	fake.getVolumesReturns = struct {
		result1 []scbe.ScbeVolumeInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeScbeRestClient) GetVolumesReturnsOnCall(i int, result1 []scbe.ScbeVolumeInfo, result2 error) {
	fake.getVolumesMutex.Lock()
	defer fake.getVolumesMutex.Unlock()
	fake.GetVolumesStub = nil
	if fake.getVolumesReturnsOnCall == nil {
		fake.getVolumesReturnsOnCall = make(map[int]struct {
			result1 []scbe.ScbeVolumeInfo
			result2 error
		})
	}
	fake.getVolumesReturnsOnCall[i] = struct {
		result1 []scbe.ScbeVolumeInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeScbeRestClient) Login() error {
	fake.loginMutex.Lock()
	ret, specificReturn := fake.loginReturnsOnCall[len(fake.loginArgsForCall)]
	fake.loginArgsForCall = append(fake.loginArgsForCall, struct {
	}{})
	fake.recordInvocation("Login", []interface{}{})
	fake.loginMutex.Unlock()
	if fake.LoginStub != nil {
		return fake.LoginStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.loginReturns
	return fakeReturns.result1
}

func (fake *FakeScbeRestClient) LoginCallCount() int {
	fake.loginMutex.RLock()
	defer fake.loginMutex.RUnlock()
	return len(fake.loginArgsForCall)
}

func (fake *FakeScbeRestClient) LoginCalls(stub func() error) {
	fake.loginMutex.Lock()
	defer fake.loginMutex.Unlock()
	fake.LoginStub = stub
}

func (fake *FakeScbeRestClient) LoginReturns(result1 error) {
	fake.loginMutex.Lock()
	defer fake.loginMutex.Unlock()
	fake.LoginStub = nil
	fake.loginReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeScbeRestClient) LoginReturnsOnCall(i int, result1 error) {
	fake.loginMutex.Lock()
	defer fake.loginMutex.Unlock()
	fake.LoginStub = nil
	if fake.loginReturnsOnCall == nil {
		fake.loginReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.loginReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeScbeRestClient) MapVolume(arg1 string, arg2 string) (scbe.ScbeResponseMapping, error) {
	fake.mapVolumeMutex.Lock()
	ret, specificReturn := fake.mapVolumeReturnsOnCall[len(fake.mapVolumeArgsForCall)]
	fake.mapVolumeArgsForCall = append(fake.mapVolumeArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	fake.recordInvocation("MapVolume", []interface{}{arg1, arg2})
	fake.mapVolumeMutex.Unlock()
	if fake.MapVolumeStub != nil {
		return fake.MapVolumeStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.mapVolumeReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeScbeRestClient) MapVolumeCallCount() int {
	fake.mapVolumeMutex.RLock()
	defer fake.mapVolumeMutex.RUnlock()
	return len(fake.mapVolumeArgsForCall)
}

func (fake *FakeScbeRestClient) MapVolumeCalls(stub func(string, string) (scbe.ScbeResponseMapping, error)) {
	fake.mapVolumeMutex.Lock()
	defer fake.mapVolumeMutex.Unlock()
	fake.MapVolumeStub = stub
}

func (fake *FakeScbeRestClient) MapVolumeArgsForCall(i int) (string, string) {
	fake.mapVolumeMutex.RLock()
	defer fake.mapVolumeMutex.RUnlock()
	argsForCall := fake.mapVolumeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeScbeRestClient) MapVolumeReturns(result1 scbe.ScbeResponseMapping, result2 error) {
	fake.mapVolumeMutex.Lock()
	defer fake.mapVolumeMutex.Unlock()
	fake.MapVolumeStub = nil
	fake.mapVolumeReturns = struct {
		result1 scbe.ScbeResponseMapping
		result2 error
	}{result1, result2}
}

func (fake *FakeScbeRestClient) MapVolumeReturnsOnCall(i int, result1 scbe.ScbeResponseMapping, result2 error) {
	fake.mapVolumeMutex.Lock()
	defer fake.mapVolumeMutex.Unlock()
	fake.MapVolumeStub = nil
	if fake.mapVolumeReturnsOnCall == nil {
		fake.mapVolumeReturnsOnCall = make(map[int]struct {
			result1 scbe.ScbeResponseMapping
			result2 error
		})
	}
	fake.mapVolumeReturnsOnCall[i] = struct {
		result1 scbe.ScbeResponseMapping
		result2 error
	}{result1, result2}
}

func (fake *FakeScbeRestClient) ServiceExist(arg1 string) (bool, error) {
	fake.serviceExistMutex.Lock()
	ret, specificReturn := fake.serviceExistReturnsOnCall[len(fake.serviceExistArgsForCall)]
	fake.serviceExistArgsForCall = append(fake.serviceExistArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("ServiceExist", []interface{}{arg1})
	fake.serviceExistMutex.Unlock()
	if fake.ServiceExistStub != nil {
		return fake.ServiceExistStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.serviceExistReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeScbeRestClient) ServiceExistCallCount() int {
	fake.serviceExistMutex.RLock()
	defer fake.serviceExistMutex.RUnlock()
	return len(fake.serviceExistArgsForCall)
}

func (fake *FakeScbeRestClient) ServiceExistCalls(stub func(string) (bool, error)) {
	fake.serviceExistMutex.Lock()
	defer fake.serviceExistMutex.Unlock()
	fake.ServiceExistStub = stub
}

func (fake *FakeScbeRestClient) ServiceExistArgsForCall(i int) string {
	fake.serviceExistMutex.RLock()
	defer fake.serviceExistMutex.RUnlock()
	argsForCall := fake.serviceExistArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeScbeRestClient) ServiceExistReturns(result1 bool, result2 error) {
	fake.serviceExistMutex.Lock()
	defer fake.serviceExistMutex.Unlock()
	fake.ServiceExistStub = nil
	fake.serviceExistReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeScbeRestClient) ServiceExistReturnsOnCall(i int, result1 bool, result2 error) {
	fake.serviceExistMutex.Lock()
	defer fake.serviceExistMutex.Unlock()
	fake.ServiceExistStub = nil
	if fake.serviceExistReturnsOnCall == nil {
		fake.serviceExistReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.serviceExistReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeScbeRestClient) UnmapVolume(arg1 string, arg2 string) error {
	fake.unmapVolumeMutex.Lock()
	ret, specificReturn := fake.unmapVolumeReturnsOnCall[len(fake.unmapVolumeArgsForCall)]
	fake.unmapVolumeArgsForCall = append(fake.unmapVolumeArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	fake.recordInvocation("UnmapVolume", []interface{}{arg1, arg2})
	fake.unmapVolumeMutex.Unlock()
	if fake.UnmapVolumeStub != nil {
		return fake.UnmapVolumeStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.unmapVolumeReturns
	return fakeReturns.result1
}

func (fake *FakeScbeRestClient) UnmapVolumeCallCount() int {
	fake.unmapVolumeMutex.RLock()
	defer fake.unmapVolumeMutex.RUnlock()
	return len(fake.unmapVolumeArgsForCall)
}

func (fake *FakeScbeRestClient) UnmapVolumeCalls(stub func(string, string) error) {
	fake.unmapVolumeMutex.Lock()
	defer fake.unmapVolumeMutex.Unlock()
	fake.UnmapVolumeStub = stub
}

func (fake *FakeScbeRestClient) UnmapVolumeArgsForCall(i int) (string, string) {
	fake.unmapVolumeMutex.RLock()
	defer fake.unmapVolumeMutex.RUnlock()
	argsForCall := fake.unmapVolumeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeScbeRestClient) UnmapVolumeReturns(result1 error) {
	fake.unmapVolumeMutex.Lock()
	defer fake.unmapVolumeMutex.Unlock()
	fake.UnmapVolumeStub = nil
	fake.unmapVolumeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeScbeRestClient) UnmapVolumeReturnsOnCall(i int, result1 error) {
	fake.unmapVolumeMutex.Lock()
	defer fake.unmapVolumeMutex.Unlock()
	fake.UnmapVolumeStub = nil
	if fake.unmapVolumeReturnsOnCall == nil {
		fake.unmapVolumeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.unmapVolumeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeScbeRestClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createVolumeMutex.RLock()
	defer fake.createVolumeMutex.RUnlock()
	fake.deleteVolumeMutex.RLock()
	defer fake.deleteVolumeMutex.RUnlock()
	fake.getVolMappingMutex.RLock()
	defer fake.getVolMappingMutex.RUnlock()
	fake.getVolumesMutex.RLock()
	defer fake.getVolumesMutex.RUnlock()
	fake.loginMutex.RLock()
	defer fake.loginMutex.RUnlock()
	fake.mapVolumeMutex.RLock()
	defer fake.mapVolumeMutex.RUnlock()
	fake.serviceExistMutex.RLock()
	defer fake.serviceExistMutex.RUnlock()
	fake.unmapVolumeMutex.RLock()
	defer fake.unmapVolumeMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeScbeRestClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ scbe.ScbeRestClient = new(FakeScbeRestClient)
